BEGIN TRANSACTION;

-- NODOS NUEVOS
INSERT OR REPLACE INTO nodo (id_nodo, titulo, descripcion, orden_secuencial, topico) VALUES
  ('nodo-6', 'Actividad especial', 'Mi primer negocio en el parque', 6, 'emprendimiento'),
  ('nodo-7', 'Actividad final', 'Construye tu ciudad con recursos públicos', 7, 'comunidad'),
  ('nodo-8', 'Actividad final', 'Mi tienda internacional', 8, 'comercio-global'),
  ('nodo-9', 'Actividad final', 'Mi mundo digital seguro', 9, 'economia-digital');

-- ACTIVIDADES DE MINIJUEGO EXISTENTES
INSERT OR REPLACE INTO actividad (id_actividad, id_nodo, tipo_actividad, puntos_otorgados, es_aleatorio, orden_secuencial) VALUES
  ('act_final_1', 'nodo-1', 'minijuego', 100, false, 1),
  ('act_final_2', 'nodo-1', 'minijuego', 100, false, 2),
  ('act_final_4', 'nodo-1', 'minijuego', 100, false, 3),
  ('act_final_5', 'nodo-1', 'minijuego', 100, false, 4),
  ('act_final_3', 'nodo-1', 'minijuego', 100, false, 5);

-- ACTIVIDADES DE MINIJUEGO NUEVAS
INSERT OR REPLACE INTO actividad (id_actividad, id_nodo, tipo_actividad, puntos_otorgados, es_aleatorio, orden_secuencial) VALUES
  ('act_final_6', 'nodo-6', 'minijuego', 120, false, 1),
  ('act_final_7', 'nodo-7', 'minijuego', 120, false, 1),
  ('act_final_8', 'nodo-8', 'minijuego', 120, false, 1),
  ('act_final_9', 'nodo-9', 'minijuego', 120, false, 1);

-- MINIJUEGOS EXISTENTES
INSERT OR REPLACE INTO minijuego (id_actividad, titulo_pantalla, historia_intro, config_json, retroalimentacion_json) VALUES
  ('act_final_1', 'La mochila del explorador', '¡Es hora de ir de excursión! Pero ten cuidado, el espacio es limitado. Solo puedes llevar 3 cosas realmente necesarias.',
    '{"tipo":"PICK_N","cantidad_requerida":3,"elementos":[{"id":"agua","nombre":"Agua","es_correcto":true,"img":"water_icon"},{"id":"dulces","nombre":"Dulces","es_correcto":false,"img":"candy_icon"},{"id":"videojuego","nombre":"Videojuego","es_correcto":false,"img":"game_icon"},{"id":"juguete","nombre":"Juguete","es_correcto":false,"img":"toy_icon"},{"id":"comida","nombre":"Comida","es_correcto":true,"img":"food_icon"},{"id":"abrigo","nombre":"Abrigo","es_correcto":true,"img":"coat_icon"}]}',
    '[{"puntos":0,"msg":"La expedición no salió muy bien, olvidaste las cosas más importantes y tuviste que esperar en el auto."},{"puntos":1,"msg":"Elegiste una cosa importante, pero te faltaron otras. ¡La próxima vez piensa en lo que realmente necesitas!"},{"puntos":2,"msg":"¡Casi lo logras! Te faltó una sola cosa para estar completamente listo."},{"puntos":3,"msg":"¡Excelente explorador! Elegiste todo lo necesario. ¡Estás listo para la aventura!"}]'),
  ('act_final_2', 'La plaza del intercambio', 'Manejas un puesto en el mercado de trueque. ¿Sabrás elegir un buen trato?',
    '{"tipo":"SEQUENTIAL_DECISION","pasos":[{"pregunta":"Alguien ofrece miel a cambio de manzanas.","respuesta_correcta":"si","contexto":"Tienes frutas frescas."},{"pregunta":"Alguien ofrece una piedra común por tus naranjas.","respuesta_correcta":"no","contexto":"Tienes naranjas jugosas."},{"pregunta":"Te ofrecen pan recién hecho por tus manzanas.","respuesta_correcta":"si","contexto":"Manzanas rojas."},{"pregunta":"Te ofrecen una cesta para fruta por unos plátanos.","respuesta_correcta":"si","contexto":"Plátanos amarillos."},{"pregunta":"Alguien quiere tus peras por un juguete roto.","respuesta_correcta":"no","contexto":"Peras dulces."}]}',
    '[{"puntos":0,"msg":"Cuidado, podrías perder tus productos en malos tratos."},{"puntos":3,"msg":"Buen trabajo en el mercado, pero algunos intercambios no fueron ideales."},{"puntos":5,"msg":"¡Maestro del trueque! Sabes reconocer el valor de las cosas perfectamente."}]'),
  ('act_final_4', 'La meta del gran ahorro', 'Tienes $20 y quieres una bicicleta de $50. ¿Podrás resistir las tentaciones y ahorrar?',
    '{"tipo":"SAVINGS_PATH","meta":50,"inicial":20,"pasos":[{"dia":"Día 1","pregunta":"Te dan $10, pero ves un dulce de $5.","opciones":[{"txt":"Comprar dulce","valor":5,"es_correcto":false},{"txt":"Guardar todo","valor":10,"es_correcto":true}]},{"dia":"Día 2","pregunta":"Un amigo vende un juguete por $8.","opciones":[{"txt":"Comprar juguete","valor":-8,"es_correcto":false},{"txt":"Seguir ahorrando","valor":0,"es_correcto":true}]},{"dia":"Día 3","pregunta":"Te dan $10, pero ves frituras de $15.","opciones":[{"txt":"Gastar dinero","valor":-15,"es_correcto":false},{"txt":"Guardar para la meta","valor":10,"es_correcto":true}]},{"dia":"Día 4","pregunta":"Ves un pastel delicioso de $20.","opciones":[{"txt":"Comprar pastel","valor":-20,"es_correcto":false},{"txt":"Guardar dinero","valor":0,"es_correcto":true}]},{"dia":"Día 5","pregunta":"Tu mamá te da $10, pero hay un cómic de $15.","opciones":[{"txt":"Comprar cómic","valor":-15,"es_correcto":false},{"txt":"No comprarlo","valor":10,"es_correcto":true}]}]}',
    '[{"puntos":0,"msg":"Qué mal, no pudiste llegar a la meta. ¡Intenta gastar menos la próxima vez!"},{"puntos":5,"msg":"¡Felicidades! Has conseguido ahorrar $50 para tu bicicleta nueva."}]'),
  ('act_final_5', 'El organizador del tesoro', 'Tienes $35. Organiza tu presupuesto para que el dinero te alcance para lo más importante.',
    '{"tipo":"CATEGORIZE","categorias":["Gasto Necesario","Gasto Opcional","Guardar/Ahorrar"],"items":[{"nombre":"Cuaderno ($10)","correcta":"Gasto Necesario"},{"nombre":"Dulces ($5)","correcta":"Gasto Opcional"},{"nombre":"Dinero que sobró","correcta":"Guardar/Ahorrar"}]}',
    '[{"puntos":0,"msg":"Tu tesoro necesita más organización. Prioriza lo necesario."},{"puntos":2,"msg":"Buen trabajo. Separar gastos ayuda a cuidar tu dinero."},{"puntos":3,"msg":"¡Gran organizador! Usas tu dinero de forma inteligente."}]'),
  ('act_final_3', 'Manejo de la Tienda', '¡Eres el dueño de la tienda! Atiende a los clientes y decide si el dinero alcanza o cuánto cambio dar.',
    '{"tipo":"SHOP_CALCULATOR","escenarios":[{"id":1,"cliente":"Doña María","articulo":"Pan artesanal","precio":12,"paga_con":20,"pregunta":"¿Cuánto es el cambio para Doña María?","cambio_correcto":8,"insuficiente":false},{"id":2,"cliente":"Pedrito","articulo":"Leche","precio":25,"paga_con":20,"pregunta":"¿Le alcanza el dinero a Pedrito?","cambio_correcto":0,"insuficiente":true}]}',
    '[{"puntos":0,"msg":"Ten cuidado con las cuentas, ¡podrías perder dinero en tu tienda!"},{"puntos":2,"msg":"¡Buen comerciante! Sabes manejar el dinero y atender a tus clientes."}]');

-- MINIJUEGOS NUEVOS CON MULTIPLE_CHOICE
INSERT OR REPLACE INTO minijuego (id_actividad, titulo_pantalla, historia_intro, config_json, retroalimentacion_json) VALUES
  ('act_final_6', 'Mi primer negocio', 'Estás empezando tu primer negocio en el parque. Debes elegir qué vender, mejorar tu producto, ser responsable y adaptarte a la demanda.',
    '{"tipo":"MULTIPLE_CHOICE","pasos":[{"pregunta":"¿Qué negocio es mejor idea en un día caluroso?","contexto":"Hace mucho calor en el parque.","opciones":[{"id":"op1","texto":"Vender sopa caliente","es_correcto":false},{"id":"op2","texto":"Vender limonada fría","es_correcto":true},{"id":"op3","texto":"Vender bufandas","es_correcto":false}]},{"pregunta":"¿Qué deberías hacer si tus clientes dicen que la limonada está muy simple?","contexto":"Tus clientes quieren más sabor.","opciones":[{"id":"op1","texto":"Ignorar a los clientes","es_correcto":false},{"id":"op2","texto":"Mejorar la receta (más sabor o azúcar)","es_correcto":true},{"id":"op3","texto":"Dejar de vender","es_correcto":false}]},{"pregunta":"¿Qué haces si un cliente compra limonada y el vaso no está limpio?","contexto":"Un cliente compró una limonada y tú te das cuenta del vaso sucio.","opciones":[{"id":"op1","texto":"Entregarlo así","es_correcto":false},{"id":"op2","texto":"Cambiarlo por uno limpio","es_correcto":true},{"id":"op3","texto":"Ignorar el problema","es_correcto":false}]},{"pregunta":"Empieza a llover y ya no hace calor. ¿Qué deberías hacer?","contexto":"La temperatura bajó significativamente.","opciones":[{"id":"op1","texto":"Seguir vendiendo lo mismo sin pensar","es_correcto":false},{"id":"op2","texto":"Cambiar tu producto (por algo caliente o diferente)","es_correcto":true},{"id":"op3","texto":"Dejar el negocio","es_correcto":false}]}]}',
    '[{"puntos":0,"msg":"Tu negocio puede mejorar. Intenta pensar en lo que quieren las personas y ser más responsable."},{"puntos":1,"msg":"Apenas comenzaste bien, pero necesitas mejorar mucho más tu atención al cliente."},{"puntos":2,"msg":"Buen trabajo. Recuerda que escuchar a los clientes y adaptarte puede mejorar tu negocio."},{"puntos":3,"msg":"¡Muy bien emprendedor! Solo te faltó un pequeño detalle para el éxito."},{"puntos":4,"msg":"¡Excelente emprendedor! Elegiste bien qué vender, escuchaste a tus clientes y tomaste buenas decisiones. Tu negocio fue un éxito."}]'),
  ('act_final_7', 'Construye tu ciudad', 'Eres parte del equipo que decide cómo usar los impuestos de tu comunidad. Tienes $50 para mejorar la ciudad.',
    '{"tipo":"MULTIPLE_CHOICE","pasos":[{"pregunta":"La ciudad necesita mejorar la educación. ¿Qué eliges?","contexto":"Tienes $50 para gastar.","opciones":[{"id":"op1","texto":"Construir un parque nuevo ($20)","es_correcto":false},{"id":"op2","texto":"Mejorar una escuela ($20)","es_correcto":true},{"id":"op3","texto":"Comprar decoraciones ($20)","es_correcto":false}]},{"pregunta":"Hay personas enfermas que necesitan atención. ¿Qué haces?","contexto":"Tienes $20 restantes.","opciones":[{"id":"op1","texto":"Invertir en un hospital ($20)","es_correcto":true},{"id":"op2","texto":"Comprar juegos","es_correcto":false},{"id":"op3","texto":"No hacer nada","es_correcto":false}]},{"pregunta":"Te quedan $10. ¿Qué opción es mejor?","contexto":"Últimos recursos para mejorar la comunidad.","opciones":[{"id":"op1","texto":"Arreglar una calle ($10)","es_correcto":true},{"id":"op2","texto":"Comprar dulces","es_correcto":false},{"id":"op3","texto":"Guardar el dinero sin usar","es_correcto":false}]},{"pregunta":"¿Qué resultado es el mejor después de usar los impuestos?","contexto":"Reflexión final sobre el gasto público.","opciones":[{"id":"op1","texto":"Gastar en cosas que solo una persona usa","es_correcto":false},{"id":"op2","texto":"Mejorar servicios que ayudan a todos","es_correcto":true},{"id":"op3","texto":"No usar el dinero","es_correcto":false}]}]}',
    '[{"puntos":0,"msg":"Tu ciudad puede mejorar. Intenta usar los impuestos en cosas que beneficien a todos."},{"puntos":1,"msg":"Apenas empezaste a tomar buenas decisiones, pero hay mucho por mejorar en tu gestión pública."},{"puntos":2,"msg":"Buen trabajo. Recuerda que usar los recursos en servicios públicos ayuda a más personas."},{"puntos":3,"msg":"¡Casi perfecto ciudadano! Solo una decisión te separó del éxito completo."},{"puntos":4,"msg":"¡Excelente ciudadano! Usaste los impuestos para mejorar tu comunidad. Ahora más personas pueden estudiar, cuidar su salud y vivir mejor."}]'),
  ('act_final_8', 'Mi tienda internacional', 'Tu tienda compra y vende productos de otros países. Decide qué importar, qué exportar y cómo usar el tipo de cambio.',
    '{"tipo":"MULTIPLE_CHOICE","pasos":[{"pregunta":"En tu ciudad no hay juguetes especiales, pero en otro país sí. ¿Qué haces?","contexto":"Oportunidad de negocios internacional.","opciones":[{"id":"op1","texto":"Importar juguetes de otro país","es_correcto":true},{"id":"op2","texto":"Ignorar los productos","es_correcto":false},{"id":"op3","texto":"Comprar lo mismo de siempre","es_correcto":false}]},{"pregunta":"Tu país produce muchas frutas. ¿Qué puedes hacer?","contexto":"Tienes exceso de producción local.","opciones":[{"id":"op1","texto":"Guardarlas todas","es_correcto":false},{"id":"op2","texto":"Exportarlas a otros países","es_correcto":true},{"id":"op3","texto":"Tirarlas","es_correcto":false}]},{"pregunta":"Quieres comprar productos de otro país, pero usan una moneda diferente. ¿Qué debes hacer?","contexto":"Necesitas realizar un tipo de cambio.","opciones":[{"id":"op1","texto":"No usar dinero","es_correcto":false},{"id":"op2","texto":"Cambiar tu dinero a la moneda del otro país","es_correcto":true},{"id":"op3","texto":"Ignorar el precio","es_correcto":false}]},{"pregunta":"Tu tienda empieza a crecer gracias a clientes de otros países. ¿Qué significa esto?","contexto":"Reflexión sobre la globalización.","opciones":[{"id":"op1","texto":"Solo vendes en tu ciudad","es_correcto":false},{"id":"op2","texto":"Estás participando en un mercado global","es_correcto":true},{"id":"op3","texto":"No estás vendiendo","es_correcto":false}]}]}',
    '[{"puntos":0,"msg":"Tu tienda puede crecer más. Intenta pensar mejor en qué comprar, vender y cómo usar el dinero."},{"puntos":1,"msg":"Apenas comprendiste los conceptos, pero necesitas aprender mucho más sobre comercio internacional."},{"puntos":2,"msg":"Buen trabajo. Recuerda que entender el tipo de cambio y las necesidades de otros países puede mejorar tu tienda."},{"puntos":3,"msg":"¡Casi un maestro! Solo te faltó un paso para dominar completamente el comercio internacional."},{"puntos":4,"msg":"¡Gran comerciante internacional! Supiste importar, exportar y usar diferentes monedas. Tu tienda ahora forma parte del mercado global."}]'),
  ('act_final_9', 'Mi mundo digital seguro', 'Usas una app en tu tablet para comprar, ahorrar, invertir y navegar. Debes tomar decisiones inteligentes y mantener tu seguridad en línea.',
    '{"tipo":"MULTIPLE_CHOICE","pasos":[{"pregunta":"Quieres comprar un accesorio para tu videojuego. ¿Dónde compras?","contexto":"Compra en línea con seguridad.","opciones":[{"id":"op1","texto":"Comprar en cualquier página","es_correcto":false},{"id":"op2","texto":"Comprar en una página confiable","es_correcto":true},{"id":"op3","texto":"Compartir tus datos con cualquiera","es_correcto":false}]},{"pregunta":"Tienes dinero guardado en tu cuenta digital. ¿Qué haces?","contexto":"Decisión sobre tu dinero futuro.","opciones":[{"id":"op1","texto":"Gastarlo todo","es_correcto":false},{"id":"op2","texto":"Guardar o invertir una parte para el futuro","es_correcto":true},{"id":"op3","texto":"Regalarlo","es_correcto":false}]},{"pregunta":"Alguien te envía un mensaje pidiendo tu contraseña. ¿Qué haces?","contexto":"Seguridad en internet.","opciones":[{"id":"op1","texto":"Compartirla","es_correcto":false},{"id":"op2","texto":"Ignorar y responder","es_correcto":false},{"id":"op3","texto":"No compartirla y avisar a un adulto","es_correcto":true}]},{"pregunta":"Quieres revisar cuánto dinero tienes. ¿Qué haces?","contexto":"Cuidado de tu información digital.","opciones":[{"id":"op1","texto":"No revisar","es_correcto":false},{"id":"op2","texto":"Usar una app segura para ver tu dinero","es_correcto":true},{"id":"op3","texto":"Adivinar","es_correcto":false}]}]}',
    '[{"puntos":0,"msg":"Tu mundo digital necesita más cuidado. Aprende a proteger tu información y usar mejor tu dinero."},{"puntos":1,"msg":"Conoces algunos conceptos, pero aún hay mucho que aprender sobre seguridad digital y finanzas."},{"puntos":2,"msg":"Vas por buen camino. Recuerda siempre cuidar tu información y pensar antes de gastar."},{"puntos":3,"msg":"¡Casi un experto! Solo te faltó un paso para ser completamente seguro en línea."},{"puntos":4,"msg":"¡Experto digital! Usaste tu dinero de forma inteligente, tomaste buenas decisiones y te mantuviste seguro en internet."}]');

COMMIT;
